global using System;
global using System.Diagnostics.Contracts;
global using System.Linq;
global using System.Threading.Tasks;
global using DiffEngine;
global using EfLocalDb;
global using Microsoft.EntityFrameworkCore;
global using NUnit.Framework;
global using VerifyTests;